import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import ResponsiveNav from "@/components/Navbar/ResponsiveNav";
import Footer from "@/components/Footer/Footer";
import Modal from "@/components/modals/Modal";
import LoginModal from "@/components/modals/LoginModal";
import SignUpModal from "@/components/modals/SignUpModal";

// Configure the font with its source files, weights, and styles
const customFont = localFont({
  src: [
    {
      path: '../public/fonts/dana-regular.woff',
      style: 'normal',
    },
    {
      path: '../public/fonts/dana-regular.woff2',
      style: 'normal',
    },
  ],
  variable: '--font-dana', // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "rpi website",
  description: "Generated by create Sina afshar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (
      <p>Yo yo</p>
    )

  return (
    <html lang="fa" dir="rtl" className={customFont.variable} suppressHydrationWarning>
      <body className="font-dana">
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <div className="bg-gradient-to-b from-slate-500 to-slate-600 min-h-screen bg-fixed">
                  <div className="w-[100%] flex flex-col mx-auto ">
                    <ResponsiveNav />
                    {children}
                    <Footer id={0} url={""} label={""} />
                  </div>
                </div>
        </ThemeProvider>

        <LoginModal 

        />
        <SignUpModal />
      </body>
    </html>
  );
}
