export const ProductsCat = [
        {
            id:1,
            label:'دیسک و صفحه',
            url:'#',
            iconurl:'/images/svgs/1.svg',
            underline : '',
            iconalt : '',

        },
        {
            id:2,
            label:'لنت ترمز',
            url:'#',
            iconurl:'/images/svgs/2.svg',
            underline : '',

        },
        {
            id:3,
            label:'تیغه برف پاک کن',
            url:'#',
            iconurl:'/images/svgs/3.svg',
            underline : '',
        },
        {
            id:4,
            label:'کاسه نمد',
            url:'#',
            iconurl:'/images/svgs/4.svg',
            underline : '',
        },
        {
            id:5,
            label:'موتور فن',
            url:'#',
            iconurl:'/images/svgs/5.svg',
            underline : '',
        },
        {
            id:6,
            label:'سوپاپ',
            url:'#',
            iconurl:'/images/svgs/7.svg',
            underline : '',
        },
        {
            id:7,
            label:'برقی',
            url:'#',
            iconurl:'/images/svgs/8.svg',
            underline : '',
        },
        {
            id:8,
            label:'شمع و وایر',
            url:'#',
            iconurl:'/images/svgs/9.svg',
            underline : '',
        },
        {
            id:9,
            label:'تسمه',
            url:'#',
            iconurl:'/images/svgs/10.svg',
            underline : '',
        },
        {
            id:10,
            label:'جلوبندی',
            url:'#',
            iconurl:'/images/svgs/11.svg',
            underline : '',
        },
        {
            id:11,
            label:'سیستم ترمز',
            url:'#',
            iconurl:'/images/svgs/12.svg',
            underline : '',
        },
        {
            id:12,
            label:'انتفال برق',
            url:'#',
            iconurl:'/images/svgs/13.svg',
            underline : '',
        },
        {
            id:13,
            label:'موتوری',
            url:'#',
            iconurl:'/images/svgs/14.svg',
            underline : '',
        },
        {
            id:14,
            label:'مجموعه سیستم فرمان',
            url:'#',
            iconurl:'/images/svgs/15.svg',
            underline : '',
        },
        {
            id:15,
            label:'لوازم جانبی',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:16,
            label:'سنسور استوپر رله',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:17,
            label:'سرسیلندر',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:18,
            label:'سیلندر',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:19,
            label:'صافی و فیلتر',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:20,
            label:'پمپ',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:21,
            label:'استارت',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:22,
            label:'انواع واشر',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
        {
            id:23,
            label:'انواع شلنگ',
            url:'#',
            iconurl:'/images/svgs/16.svg',
            underline : '',
        },
];